spring:
  application:
    name: analytics-service
  profiles:
    include: common
  
  # Batch processing configuration
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:h2:mem:analyticsdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 

server:
  port: 8086

# Analytics service specific configuration
analytics:
  clickhouse:
    url: ${CLICKHOUSE_URL:jdbc:clickhouse://localhost:8123/gaming}
    username: ${CLICKHOUSE_USERNAME:default}
    password: ${CLICKHOUSE_PASSWORD:}
  batch:
    chunk-size: ${BATCH_CHUNK_SIZE:1000}
    core-pool-size: ${BATCH_CORE_POOL_SIZE:2}
    max-pool-size: ${BATCH_MAX_POOL_SIZE:4}
  kafka:
    streams:
      application-id: analytics-processor
      num-stream-threads: 2

