global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # TicTacToe services (when running locally)
  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  - job_name: 'lobby-service'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  - job_name: 'game-service'
    static_configs:
      - targets: ['host.docker.internal:8084']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  - job_name: 'leaderboard-service'
    static_configs:
      - targets: ['host.docker.internal:8085']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['host.docker.internal:8086']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # Infrastructure services
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka:9092']
